server:
  port: 8500
spring:
  application:
    name: gateway-server
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: borrow-service
          uri: lb://borrow-service
          predicates:
            - Path=/borrow/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka