server:
  port: 8801
eureka:
  instance:
    hostname: eureka-1
  client:
    fetch-registry: false
#    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-2:8802/eureka
spring:
  application:
    name: eureka-server